POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "Charlie",
  "email": "mistachalie@gmail.com",
  "password": 123456,
  "interest": "football"
}

###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "mistachalie@gmail.com",
  "password": "123456"
}